#CLI

$kubectl autoscaling <deployment ou rs> <deployment name> —min=<min pod> —max=<max pod> —cp-percent=<number with percent>
$kubectl autoscaling rs container-dpt --min=2 --max=5 --cpu-percent=80%             

#Get HPA
$ kubectl get hpa

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50


