kind: ConfigMap
apiVersion: v1
metadata:
    name: example-config
    namespace: default
data:
# example of a simple property defined using --from-literal
    example.property.1: hello
    example.property.2: world

# example of a complex property defined using --from-file
example.property.file:
property.1=value-1
property.2=value-2
property.3=value-3

#COMANDS
$ kubectl create configmap game-config-3 --from-file=game-special-key=docs/user-guide/configmap/kubectl/game.properties
$ kubectl get configmaps game-config-3 -o yaml